version: '3.8'
name: mezon-top-board-dev

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.debug
    container_name: backend
    volumes:
      - ./backend:/app
      - be_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment:
      PORT: 8123
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI}
      OAUTH2_API_URL: ${OAUTH2_API_URL}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRES_IN_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRES_IN_MINUTES}
      JWT_REFRESH_TOKEN_EXPIRES_IN_MINUTES: ${JWT_REFRESH_TOKEN_EXPIRES_IN_MINUTES}
    ports:
      - "8123:8123"
    networks:
      - main_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    container_name: frontend
    volumes:
      - ./frontend:/app
      - fe_node_modules:/app/node_modules
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "3000:3000"
    networks:
      - main_net

volumes:
  postgres_data:
  fe_node_modules:
  be_node_modules:

networks:
  main_net: