name: Deploy FE to Prodction Top Mezon AI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-prod-fe.yml'
jobs:
  deploy:
    runs-on: top-prod
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Node Module
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json,**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-  

    - name: Update Env-Config
      run: |
        cd frontend/
        echo '${{ secrets.ENV_PROD_FE }}' > .env
        cp .env /var/www/top-mezon-ai/

    - name: Build FE & Deploy
      run: |
        cd frontend/
        yarn
        yarn build
        cp -r dist/* /var/www/top-mezon-ai/
