name: Deploy to Development Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: SSH into server and deploy application
      env:
        SERVER_PASSWORD: ${{ secrets.Development.SERVER_PASSWORD }}
        SERVER_USER: ${{ secrets.Development.SERVER_USER }}
        SERVER_HOST: ${{ secrets.Development.SERVER_HOST }}
      run: |
        sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} << EOF
          cd ~/mezon-top-board
          git pull origin dev
          ./docker-up.sh --build --core
          docker system prune -f
        EOF